# Generated by Django 6.1 on 2026-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of primary guest', max_length=120)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=30)),
                ('room', models.CharField(choices=[('Nordic Standard Suite', 'Nordic Standard Suite'), ('Deluxe Lakeview Suite', 'Deluxe Lakeview Suite'), ('Grand Haven Suite', 'Grand Haven Suite'), ('Forest Eco Villa', 'Forest Eco Villa'), ('Royal Penthouse Suite', 'Royal Penthouse Suite')], help_text='Selected room type', max_length=60)),
                ('check_in', models.DateField(help_text='Check-in date')),
                ('check_out', models.DateField(help_text='Check-out date')),
                ('guests', models.PositiveIntegerField(default=1, help_text='Number of guests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
